### ISSUE TITLE
update button does not save settings for HID powersploit attack

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/nethunter-app#121]
so the most recent update to the nethunter app for what ever reason does not save the configuration for powersploit or does not load it at run time because upon exiting and restarting the app the fields are not repopulated.

**Comment by binkybear** [comment]
I'm debating if this is really a bug or not because we previously would save the configuration into the powershell exploit itself.  However, because we have to pass the shellcode now separate  we don't save those settings in the ps1 file.  Before regex would be used in the exploit to get those settings but we don't do that anymore.

I think it might be more of an enhancement at this point but I will let others chime in.

**Comment by thesle3p** [comment]
Why not have the shell code saved to a file when generated then read and
piped out to invoke shellcode? I bring this up because on a red team
engagement you don't always have time to sit around and wait for
shellcode to be generated, especially if you are compromising multiple
systems in a row.

**Comment by binkybear** [comment]
Ha! Just noticed we had the same type of idea. Going to mark this duplicate for now since we are already discussing it in https://github.com/offensive-security/nethunter-app/issues/114#issuecomment-176519338
