### ISSUE TITLE
"Script to execute:" -   Where edit?

### ISSUE THREAD

**Issue by serpunja** [offensive-security/nethunter-app#163]
**Where this file?:**
![p_20170304_163542](https://cloud.githubusercontent.com/assets/24878620/23579266/ca105d48-00fa-11e7-8ce7-cb485dd12cd5.jpg)

**It does not correct command:**
![p_20170304_164914](https://cloud.githubusercontent.com/assets/24878620/23579269/e785befe-00fa-11e7-8bd6-5e9750af1e6d.jpg)
**Tell me please.**
 **As the name of this file ?**  In Nethunter .

**Comment by jmingov** [comment]
Hi @serpunja, 

Looks like the hostapd-wpe package is no installed.

As you can see here, http://tools.kali.org/wireless-attacks/hostapd-wpe it is a kali package, try doing `apt-get install hostapd-wpe` inside a kali terminal as root, that sould fix the problem.

You cant change the comand executed since its harcoded inside the nethunter app. 

See https://github.com/offensive-security/nethunter-app/blob/master/src/com/offsec/nethunter/ManaFragment.java#L168

**Comment by serpunja** [comment]
@jmingov  O.K
