### ISSUE TITLE
Latest nethunter.apk not working on Android 6.0 Marshmallow

### ISSUE THREAD

**Issue by lavanoid** [offensive-security/nethunter-app#211]
The current version of the nethunter APK doesn't work on my device (HTC One M8), which is running Android 6.0. After flashing the nethunter zip, the Nethunter app doesn't show on the app drawer and neither will it install when I attempt to install the APK manually. 

Currently the only workaround I have is to install an older version of the APK, such as this one: https://github.com/offensive-security/kali-nethunter/raw/66d40bfbc3ba09d0611f400cc9c49f00d5334767/nethunter-installer/update/data/app/nethunter.apk

**Comment by Re4son** [comment]
Might be the installer, rather the apk itself. I need your help to locate the issues if that's ok with you.
By "current version", do you mean release [2019.1](https://github.com/offensive-security/nethunter-app/releases/tag/v2019.1)?

Did you build the nethunter zip yourself? If so, which "kali-nethunter" branch did you use?

What happens if you uninstall the old apk and manually install the current version?

**Comment by lavanoid** [comment]
By "current", I am referring to this one: https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/data/app/nethunter.apk

I built the Nethunter zip myself and I used the branch I used was the "master" branch. When I uninstall the old APK, the device still refuses to install the currently available version.

**Comment by Re4son** [comment]
Do you get an error message during installation?

**Comment by lavanoid** [comment]
0_o Now it installed, after manually installing the APK again. Very odd. Also, sometimes after flashing the .zip and boot the device, I have to reboot it again for Nethunter to appear in the app drawer. No idea what that is all about. 

I'm going to assume that the ROM I'm using is a bit temperamental.I guess this issue can be closed.

**Comment by Re4son** [comment]
Glad to hear that it's working.
